version: "3.8"

services:
  nginx:
    build:
      target: proxy-dev
    ports:
      - 8080:80

  nodejs-app:
    build:
      target: dev
    volumes:
      - ./server/src:/home/node/app/src
      - ./server/package.json:/home/node/app/package.json
      - ./server/package-lock.json:/home/node/app/package-lock.json
      - ./server/tsconfig.json:/home/node/app/tsconfig.json
    ports:
      - 5000:5000

  webpack-dev-server:
    build:
      context: client
      target: dev
    volumes:
      - ./client/public:/home/node/app/public
      - ./client/src:/home/node/app/src
      - ./client/package.json:/home/node/app/package.json
      - ./client/package-lock.json:/home/node/app/package-lock.json
      - ./client/tsconfig.json:/home/node/app/tsconfig.json
      - ./client/.env:/home/node/app/.env
    ports:
      - 3000:3000
